name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      
      - name: Build Go application
        run: go build -o myapp

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          # Build and push Docker image for yourusername
          docker build -t yourusername/myapp:latest .
          docker push yourusername/myapp:latest

          # Build and push Docker image for leelingesh
          docker build -t leelingesh/myapp:latest .
          docker push leelingesh/myapp:latest
