name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      
      - name: Build Go application
        run: go build -o myapp

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for yourusername
        run: |
          docker build -t yourusername/myapp:latest .
          docker tag yourusername/myapp:latest yourusername/myapp:$(date +%s)

      - name: Push Docker image for yourusername
        run: docker push yourusername/myapp

      - name: Build Docker image for leelingesh
        run: |
          docker build -t leelingesh/myapp:latest .
          docker tag leelingesh/myapp:latest leelingesh/myapp:$(date +%s)

      - name: Push Docker image for leelingesh
        run: docker push leelingesh/myapp
